name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '17'

    - name: Build application
      run: mvn clean package -DskipTests

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd Spring-security
          git pull origin main
          mvn clean package -DskipTests
          pkill -f 'java -jar' || true
          JAR=$(ls target/*.jar | head -n 1)
          echo "Running $JAR"
          nohup java -jar $JAR > app.log 2>&1 &
